import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-950">
        <main className="fixed flex h-full w-full items-center justify-center">
          <section className="rounded-lg border border-white p-4 text-white">
            {children}
          </section>
        </main>
      </body>
    </html>
  )
}
